# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region_Surge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_hash', models.CharField(max_length=32)),
                ('demand', models.IntegerField()),
                ('supply', models.IntegerField()),
                ('surge', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
